//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by obedit.rc
//
#define ID_APPLY_BUTTON                 3
#define ID_CLEAR_BUTTON                 3
#define IDD_ABOUTBOX                    100
#define IDD_OBEDIT_FORM                 101
#define IDD_ERRORBAR                    103
#define IDR_MAINFRAME                   128
#define IDR_OBEDITTYPE                  129
#define IDD_LOAD_DLG                    130
#define IDD_PROGRESS_DLG                131
#define IDR_RECORDTREE_MENU             132
#define IDB_FOLDER                      132
#define IDR_RECORDLIST_MENU             133
#define IDD_OBERROR_DLG                 133
#define IDB_FILE                        133
#define IDD_FILETREE_DLG                134
#define IDD_FINDBINARY_DLG              135
#define IDD_ARMOR_VIEW                  136
#define IDI_ARMOR                       136
#define IDD_BIPEDPARTS_DLG              137
#define IDD_SELECTRECORD_DLG            138
#define IDD_PROMPT_DLG                  139
#define IDD_BIPEDPARTSLIST_DLG          140
#define IDR_DEFAULT_RECORD_ACCEL        140
#define IDD_UNDOBAR                     141
#define IDD_INPUT_DLG                   142
#define IDD_BATCHEDIT_DLG               143
#define IDD_FIND_DLG                    145
#define IDI_FIND                        145
#define IDD_LVLI_VIEW                   149
#define IDR_LVLITEMLIST_MENU            150
#define IDD_LVLEDIT_DLG                 150
#define IDR_LVLI_ACCELERATOR            151
#define IDR_EFFECTLIST_MENU             151
#define IDR_EFFECT_ACCELERATOR          152
#define IDD_SPEL_VIEW                   152
#define IDD_EFFECT_DLG                  153
#define IDD_SCPT_VIEW                   154
#define IDD_INGR_VIEW                   155
#define IDD_ALCH_VIEW                   156
#define IDR_BOOK_MENU                   156
#define IDD_LVSP_VIEW                   157
#define IDR_SCRIPT_MENU                 157
#define IDD_LVLC_VIEW                   158
#define IDD_ENCH_VIEW                   159
#define IDD_AMMO_VIEW                   160
#define IDD_APPA_VIEW                   161
#define IDD_BOOK_VIEW                   162
#define IDD_CLOT_VIEW                   163
#define IDD_KEYM_VIEW                   164
#define IDD_MISC_VIEW                   165
#define IDD_SGST_VIEW                   166
#define IDD_SLGM_VIEW                   167
#define IDD_WEAP_VIEW                   168
#define IDD_ACTI_VIEW                   169
#define IDD_STAT_VIEW                   170
#define IDD_CONT_VIEW                   171
#define IDD_CNTOEDIT_DLG                172
#define IDD_SOUN_VIEW                   173
#define IDD_FLOR_VIEW                   174
#define IDD_FURN_VIEW                   175
#define IDD_RESOURCE_VIEW               176
#define IDD_LIGH_VIEW                   177
#define IDD_SCRIPTERROR_VIEW            178
#define IDC_RECORDTREE                  1000
#define IDC_RESOURCE_TREE               1001
#define IDC_RECORDLIST                  1002
#define IDC_HBAR                        1003
#define IDC_VEDGE                       1004
#define IDC_FILENAME                    1005
#define IDC_FILE_LIST                   1006
#define IDC_FILESIZE                    1007
#define IDC_FILETIME                    1008
#define IDC_FILE_PROGRESS               1009
#define IDC_FILE_LABEL                  1010
#define IDC_PREVIEW_RICHEDIT            1011
#define IDC_FILE_PERCENT                1012
#define IDC_PREVIEW_IMAGE               1013
#define IDC_MESSAGE                     1014
#define IDC_DETAILS                     1015
#define IDC_TREECTRL                    1016
#define IDC_BINARYDATA_TEXT             1017
#define IDC_SETACTIVE                   1018
#define ID_SAVE_BUTTON                  1019
#define ID_CANCEL_BUTTON                1020
#define IDC_BIPEDPART_1                 1021
#define ID_COMPILE_BUTTON               1021
#define ID_UNCHECKALL_BUTTON            1022
#define ID_FIND_BUTTON                  1023
#define IDC_BIPEDPART_2                 1024
#define ID_CHECKALL_BUTTON              1025
#define IDC_BIPEDPART_3                 1026
#define IDC_PREVIOUS_TEXT               1027
#define IDC_BIPEDPART_4                 1028
#define IDC_CURRENT_TEXT                1029
#define ID_BUTTON1                      1030
#define IDC_BIPEDPART_5                 1031
#define ID_BUTTON2                      1032
#define IDC_PREVIOUS_FORMID             1033
#define IDC_BIPEDPART_6                 1034
#define ID_BUTTON3                      1035
#define IDC_CURRENT_FORMID              1036
#define IDC_BIPEDPART_7                 1037
#define IDC_LABEL                       1038
#define IDC_BIPEDPART_8                 1039
#define IDC_TYPE_LIST                   1040
#define IDC_BIPEDPART_9                 1041
#define IDC_BIPEDPART_10                1042
#define IDC_BIPED_LIST                  1043
#define IDC_BIPEDPART_11                1044
#define IDC_BIPEDPART_12                1045
#define IDC_INPUTTEXT                   1046
#define IDC_BIPEDPART_13                1047
#define IDC_FIELD_LIST                  1048
#define IDC_BIPEDPART_14                1049
#define IDC_BATCH_EDIT                  1050
#define IDC_BIPEDPART_15                1051
#define IDC_FIND_LIST                   1052
#define IDC_EDITORID                    1053
#define IDC_BIPEDPART_16                1054
#define IDC_FULLNAME                    1054
#define IDC_BINARY_CHECK                1055
#define IDC_FORMID                      1056
#define IDC_SEARCH_COMBO                1057
#define IDC_CALCULATEALL                1058
#define IDC_LEVEL                       1059
#define IDC_CASESENSITIVE_CHECK         1060
#define IDC_CALCULATEEACH               1061
#define IDC_COUNT                       1062
#define IDC_FIND_LABEL                  1063
#define IDC_CHANCENONE                  1064
#define IDC_OBJECT_FORMID               1065
#define IDC_ITEM_LIST                   1066
#define ID_DELETE_BUTTON                1067
#define IDC_FORMID2                     1068
#define IDC_ENCHANT_TYPE                1069
#define IDC_WEIGHT                      1070
#define IDC_AUTOCALC                    1071
#define IDC_USEALLSPELLS                1072
#define IDC_VALUE                       1073
#define IDC_CHARGE                      1074
#define IDC_FOV                         1074
#define IDC_AREA                        1075
#define IDC_RADIUS                      1075
#define IDC_HEALTH                      1076
#define IDC_FALLOFF                     1076
#define IDC_COST                        1077
#define IDC_HOSTILE                     1078
#define IDC_EFFECT_LIST                 1079
#define IDC_ENCHANTCHARGE               1080
#define IDC_NAME                        1081
#define IDC_RANGE_LIST                  1082
#define IDC_SPELL_LEVEL                 1083
#define IDC_BIPEDPARTS                  1084
#define IDC_DURATION                    1085
#define IDC_WEIGHT2                     1086
#define IDC_NOABSORBREFLECT             1087
#define IDC_MAGNITUDE                   1088
#define IDC_VALUE2                      1089
#define IDC_SCRIPTALWAYSAPPLIES         1090
#define IDC_ACTORVALUE_LIST             1091
#define IDC_FOODITEM                    1092
#define IDC_AREAIGNORESLOS              1093
#define IDC_USES                        1094
#define IDC_ENCHANTMENT                 1095
#define IDC_EFFECTNAME                  1096
#define IDC_SILENCEIMMUNE               1097
#define IDC_SCHOOL_LIST                 1098
#define IDC_PCSTARTSPELL                1099
#define IDC_VISUALEFFECT_LIST           1100
#define IDC_SCRIPT                      1101
#define IDC_SCRIPT_LIST                 1102
#define IDC_EDIT_ENCHANTMENT            1103
#define IDC_MAGPRECENT                  1104
#define IDC_CREATURETEMPLATE            1105
#define IDC_SOUND                       1106
#define IDC_INGREDIANT                  1107
#define IDC_EDIT_SCRIPT                 1108
#define IDC_SCRIPT_TEXT                 1109
#define IDC_BIPEDPARTS_BUTTON           1110
#define IDC_EDIT_CREATURETEMPLATE       1111
#define IDC_EDIT_INGREDIANT             1112
#define IDC_MODEL                       1113
#define IDC_HIDERINGS                   1114
#define IDC_EDIT_CLOSESOUND             1115
#define IDC_HIDEAMULET                  1116
#define IDC_SPELL_TYPE                  1117
#define IDC_ARMOR                       1118
#define IDC_FLICKERTYPE                 1118
#define IDC_MALEBIPED                   1119
#define IDC_REDSPIN                     1119
#define IDC_DAMAGE                      1120
#define IDC_GREENSPIN                   1120
#define IDC_CREDITS                     1120
#define IDC_MALEWORLD                   1121
#define IDC_BLUESPIN                    1121
#define IDC_STATUS_TEXT                 1121
#define IDC_SPEED                       1122
#define IDC_MALEICON                    1123
#define IDC_ERRORTEXT                   1123
#define IDC_IGNORERESIST                1124
#define IDC_REACH                       1125
#define IDC_FEMALEWORLD                 1126
#define IDC_QUALITY                     1127
#define IDC_FEMALEICON                  1128
#define IDC_TYPE                        1129
#define IDC_FEMALEBIPED                 1130
#define IDC_PLAYABLE                    1131
#define IDC_QUESTITEM                   1132
#define IDC_SELECTENCHANT_BUTTON        1133
#define IDC_DANGEROUS                   1134
#define IDC_CARRIED                     1135
#define IDC_SELECTSCRIPT_BUTTON         1136
#define IDC_SELECTCREATURE_BUTTON       1137
#define IDC_TEACHES_LIST                1138
#define IDC_SELECTSOUND_BUTTON          1139
#define IDC_SELECTINGREDIANT_BUTTON     1140
#define IDC_INVENTORYICON               1141
#define IDC_SELECTCLOSESOUND_BUTTON     1142
#define IDC_SCROLL                      1143
#define IDC_CANTBETAKEN                 1144
#define IDC_BOOKTEXT                    1145
#define IDC_CAPACITY                    1146
#define IDC_SOUL                        1147
#define IDC_IGNORESRESIST               1148
#define IDC_RESPAWNS                    1149
#define IDC_OPENSOUND                   1150
#define IDC_CLOSESOUND                  1151
#define IDC_SELECTOPENSOUND_BUTTON      1152
#define IDC_EDIT_OPENSOUND              1153
#define IDC_SOUNDFILE                   1154
#define IDC_MINATTENUATION              1155
#define IDC_MAXATTENUATION              1156
#define IDC_STATICATTENUATION           1157
#define IDC_FREQADJUSTMENT              1158
#define IDC_RANDOMFREQSHIFT             1159
#define IDC_RANDOMPLAY                  1160
#define IDC_RANDOMLOCATION              1161
#define IDC_LOOP                        1162
#define IDC_MENUSOUND                   1163
#define IDC_IGNOREENVIRONMENT           1164
#define IDC_2DSOUND                     1165
#define IDC_360LFE                      1166
#define IDC_STARTTIME                   1167
#define IDC_STOPTIME                    1168
#define IDC_MINATT_SLIDER               1169
#define IDC_MAXATT_SLIDER               1170
#define IDC_SPRING                      1171
#define IDC_STATATT_SLIDER              1172
#define IDC_SUMMER                      1173
#define IDC_STARTTIME_SLIDER            1174
#define IDC_FALL                        1175
#define IDC_STOPTIME_SLIDER             1176
#define IDC_WINTER                      1177
#define IDC_SELECT_MALEWORLDMODEL       1178
#define IDC_SELECT_MALEBIPEDMODEL       1179
#define IDC_TIME                        1180
#define IDC_SELECT_MODEL                1181
#define IDC_SELECT_MALEICON             1182
#define IDC_SELECT_ICON                 1183
#define IDC_SELECT_FEMALEBIPEDMODEL     1184
#define IDC_OFFBYDEFAULT                1185
#define IDC_NEGATIVE                    1186
#define IDC_SELECT_FEMALEWORLDMODEL     1187
#define IDC_DYNAMIC                     1188
#define IDC_SELECT_FEMALEICON           1189
#define IDC_FLICKER                     1190
#define IDC_SPOTLIGHT                   1191
#define IDC_SPOTSHADOW                  1192
#define IDC_FLICKERSLOW                 1193
#define IDC_PULSE                       1194
#define IDC_PULSESLOW                   1195
#define IDC_FLICKERNONE                 1196
#define IDC_FADE                        1197
#define IDC_RED                         1198
#define IDC_GREEN                       1199
#define IDC_BLUE                        1200
#define IDC_COLOR                       1201
#define IDC_SELECT_SOUNDFILE            1202
#define IDC_EDIT_SOUND                  1203
#define IDS_TT_EDITORID                 15000
#define IDS_TT_FULLNAME                 15001
#define IDS_TT_FORMID                   15002
#define IDS_TT_ARMORTYPE                15003
#define IDS_TT_ARMOR                    15004
#define IDS_TT_VALUE                    15005
#define IDS_TT_WEIGHT                   15006
#define IDS_TT_HEALTH                   15007
#define IDS_TT_ENCHANTMENT              15008
#define IDS_TT_SCRIPT                   15009
#define IDS_TT_PLAYABLE                 15010
#define IDS_TT_HIDERINGS                15011
#define IDS_TT_HIDEAMULET               15012
#define IDS_TT_MALEICON                 15013
#define IDS_TT_FEMALEICON               15014
#define IDS_TT_BIPED                    15015
#define IDS_TT_QUESTITEM                15016
#define IDS_TT_MODEL                    15017
#define IDS_TT_MALEWORLDMODEL           15018
#define IDS_TT_FEMALEWORLDMODEL         15019
#define IDS_TT_MALEBIPEDMODEL           15020
#define IDS_TT_FEMALEBIPEDMODEL         15021
#define IDS_TT_SAVE                     15022
#define IDS_TT_APPLY                    15023
#define IDS_TT_CANCEL                   15024
#define IDS_TT_EDITBIPED                15025
#define IDS_TT_EDITSCRIPT               15026
#define IDS_TT_SELECTSCRIPT             15027
#define IDS_TT_EDITENCHANT              15028
#define IDS_TT_SELECTENCHANT            15029
#define IDS_TT_SOUND                    15030
#define IDS_TT_DANGEROUS                15031
#define IDS_TT_FOODITEM                 15032
#define IDS_TT_AUTOCALC                 15033
#define IDS_TT_DAMAGE                   15034
#define IDS_TT_SPEED                    15035
#define IDS_TT_ENCHANTPOINTS            15036
#define IDS_TT_IGNORERESIST             15037
#define IDS_TT_QUALITY                  15038
#define IDS_TT_APPATYPE                 15039
#define IDS_TT_SCROLL                   15040
#define IDS_TT_NOTAKE                   15041
#define IDS_TT_TEACHES                  15042
#define IDS_TT_CONTRESPAWNS             15043
#define IDS_TT_OPENSOUND                15044
#define IDS_TT_CLOSESOUND               15045
#define IDS_TT_ENCHTYPE                 15046
#define IDS_TT_COST                     15047
#define IDS_TT_CHARGE                   15048
#define IDS_TT_INGREDIENT               15049
#define IDS_TT_SPRING                   15050
#define IDS_TT_SUMMER                   15051
#define IDS_TT_FALL                     15052
#define IDS_TT_WINTER                   15053
#define IDS_TT_CALCEACH                 15054
#define IDS_TT_CALCALL                  15055
#define IDS_TT_CHANCENONE               15056
#define IDS_TT_CREATURETEMPLATE         15057
#define IDS_TT_USEALLSPELLS             15058
#define IDS_TT_SCPTTYPE                 15059
#define IDS_TT_USES                     15060
#define IDS_TT_CAPACITY                 15061
#define IDS_TT_SOUL                     15062
#define IDS_TT_SOUNDFILE                15063
#define IDS_TT_MINATTENUATION           15064
#define IDS_TT_MAXATTENUATION           15065
#define IDS_TT_STATICATTENUATION        15066
#define IDS_TT_FREQADJUSTMENT           15067
#define IDS_TT_STARTTIME                15068
#define IDS_TT_STOPTIME                 15069
#define IDS_TT_RANDOMFREQSHIFT          15070
#define IDS_TT_RANDOMPLAY               15071
#define IDS_TT_RANDOMLOCATION           15072
#define IDS_TT_LOOP                     15073
#define IDS_TT_MENUSOUND                15074
#define IDS_TT_IGNOREENVIRONMENT        15075
#define IDS_TT_2DSOUND                  15076
#define IDS_TT_360LFE                   15077
#define IDS_TT_SPELTYPE                 15078
#define IDS_TT_LEVEL                    15079
#define IDS_TT_IGNORELOS                15080
#define IDS_TT_NOABSORBREFLECT          15081
#define IDS_TT_PCSTARTSPELL             15082
#define IDS_TT_SCRIPTALWAYSAPPLIES      15083
#define IDS_TT_SILENCEIMMUNE            15084
#define IDS_TT_WEAPTYPE                 15085
#define IDS_TT_REACH                    15086
#define IDS_TT_ICON                     15087
#define IDS_TT_SELECTCREATURE           15088
#define IDS_TT_EDITCREATURE             15089
#define IDS_TT_EDITSOUND                15090
#define IDS_TT_SELECTSOUND              15091
#define IDS_TT_EDITINGREDIENT           15092
#define IDS_TT_SELECTINGREDIENT         15093
#define IDS_TT_FADE                     15094
#define IDS_TT_REDCOLOR                 15095
#define IDS_TT_GREENCOLOR               15096
#define IDS_TT_BLUECOLOR                15097
#define IDS_TT_TIME                     15098
#define IDS_TT_OFFBYDEFAULT             15099
#define IDS_TT_FLICKER                  15100
#define IDS_TT_SPOTLIGHT                15101
#define IDS_TT_SPOTSHADOW               15102
#define IDS_TT_DYNAMIC                  15103
#define IDS_TT_NEGATIVE                 15104
#define IDS_TT_COLORBOX                 15105
#define IDS_TT_CARRIED                  15106
#define IDS_TT_FLICKERTYPE              15107
#define IDS_TT_FOV                      15108
#define IDS_TT_FALLOFF                  15109
#define IDS_TT_RADIUS                   15110
#define ID_FILE_IMPORT_CSV              32772
#define ID_FILE_EXPORT_SELECTEDITEMS    32773
#define ID_FILE_EXPORTCSV_SELECTEDITEMS 32774
#define ID_FILE_EXPORTCSV_ALLITEMS      32775
#define ID_FILE_EXPORTCSV_ITEMTYPE      32776
#define ID_FILE_EXPORTCSV_SELECTEDITEMS2 32776
#define ID_RECORDTREE_RELOAD            32777
#define ID_RECORDTREE_EXPORTTOCSV       32778
#define ID_VIEW_FILESTRUCTURE           32779
#define ID_FILE_EXPORT_CSVEXTERIORLOCATIONS 32780
#define ID_FILE_EXPORT_CSVEXTMAPMARKERS 32781
#define ID_HELP_TESTFIELDLOOKUP         32782
#define ID_FILE_EXPORT_CSVEXPORTEXTERIORPLANTS 32783
#define ID_EDIT_FINDBINARYDATA          32784
#define ID_HELP_TESTFINDFORMID          32785
#define ID_EDIT_SELECTALL               32786
#define ID_VIEW_ERROR_BAR               32787
#define ID_TEST_MEMORYSPEED             32788
#define ID_TEST_TOKENSCRIPTS            32789
#define ID_MENU_CLEAN                   32790
#define ID_RECORD_CLEAN                 32791
#define ID_RECORD_MOVEACTIVE            32792
#define ID_MENU_EDITRECORD              32794
#define ID_MENU_NEWRECORD               32795
#define ID_EDIT_NEWRECORD               32796
#define ID_RECORD_TOGGLEDELETE          32797
#define ID_MENU_TOGGLEIGNORE            32798
#define ID_RECORD_TOGGLEIGNORE          32800
#define ID_MENU_TOGGLEQUEST             32801
#define ID_RECORD_TOGGLEQUEST           32802
#define ID_VIEW_UNDOBAR                 32803
#define ID_RECORD_RENAME                32804
#define ID_RECORD_CREATECOPY            32805
#define ID_RECORD_BATCHEDIT             32806
#define ID_LVLOLIST_DELETE              32807
#define ID_LVLLIST_DELETE               32808
#define ID_LVLLIST_ADD                  32809
#define ID_LVLLIST_EDIT                 32810
#define ID_DELETE_ITEM                  -32724
#define ID_ADD_COUNT                    32813
#define ID_MINUS_COUNT                  32814
#define ID_ADD_LEVEL                    32815
#define ID_MINUS_LEVEL                  32816
#define ID_LVL_EDITRECORD               32818
#define ID_LVLLIST_EDITRECORD           32819
#define ID_EFFECTLIST_EDIT              32820
#define ID_EFFECTLIST_ADD               32821
#define ID_EFFECTLIST_DELETE            32822
#define ID_EFFECTLIST_EDITSCRIPT        32824
#define ID_HELP_TESTOUTPUTEFFECTS       32825
#define ID_VIEW_RESOURCEVIEWER          32828
#define ID_HELP_TESTRECORDSIZE          32829
#define ID_HELP_UESPWIKI                32831
#define ID_HELP_CSWIKI                  32832
#define ID_TEST_CLEANRECOMPILEALL       32834
#define ID_TEST_RECOMPILEALL            32835
#define ID_HELP_TESTCOMPARESCRIPTS      32836
#define ID_VIEW_RESETLISTS              32837

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
